/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForSoloRouteImport } from './routes/for-solo'
import { Route as ForFloorsRouteImport } from './routes/for-floors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSocialRouteImport } from './routes/dashboard.social'
import { Route as DashboardPlatformRouteImport } from './routes/dashboard.platform'
import { Route as DashboardOpsRouteImport } from './routes/dashboard.ops'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardConciergeRouteImport } from './routes/dashboard.concierge'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as BookSalonKeyRouteImport } from './routes/book.$salonKey'
import { Route as DashboardSocialIndexRouteImport } from './routes/dashboard.social.index'
import { Route as DashboardSocialStudioRouteImport } from './routes/dashboard.social.studio'
import { Route as DashboardSocialScheduleRouteImport } from './routes/dashboard.social.schedule'
import { Route as DashboardSocialCampaignsRouteImport } from './routes/dashboard.social.campaigns'
import { Route as DashboardSocialBrandRouteImport } from './routes/dashboard.social.brand'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSoloRoute = ForSoloRouteImport.update({
  id: '/for-solo',
  path: '/for-solo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFloorsRoute = ForFloorsRouteImport.update({
  id: '/for-floors',
  path: '/for-floors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSocialRoute = DashboardSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlatformRoute = DashboardPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpsRoute = DashboardOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConciergeRoute = DashboardConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSalonKeyRoute = BookSalonKeyRouteImport.update({
  id: '/book/$salonKey',
  path: '/book/$salonKey',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSocialIndexRoute = DashboardSocialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSocialRoute,
} as any)
const DashboardSocialStudioRoute = DashboardSocialStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => DashboardSocialRoute,
} as any)
const DashboardSocialScheduleRoute = DashboardSocialScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardSocialRoute,
} as any)
const DashboardSocialCampaignsRoute =
  DashboardSocialCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => DashboardSocialRoute,
  } as any)
const DashboardSocialBrandRoute = DashboardSocialBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => DashboardSocialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/for-floors': typeof ForFloorsRoute
  '/for-solo': typeof ForSoloRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/book/$salonKey': typeof BookSalonKeyRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/concierge': typeof DashboardConciergeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/ops': typeof DashboardOpsRoute
  '/dashboard/platform': typeof DashboardPlatformRoute
  '/dashboard/social': typeof DashboardSocialRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/social/brand': typeof DashboardSocialBrandRoute
  '/dashboard/social/campaigns': typeof DashboardSocialCampaignsRoute
  '/dashboard/social/schedule': typeof DashboardSocialScheduleRoute
  '/dashboard/social/studio': typeof DashboardSocialStudioRoute
  '/dashboard/social/': typeof DashboardSocialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-floors': typeof ForFloorsRoute
  '/for-solo': typeof ForSoloRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/book/$salonKey': typeof BookSalonKeyRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/concierge': typeof DashboardConciergeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/ops': typeof DashboardOpsRoute
  '/dashboard/platform': typeof DashboardPlatformRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/social/brand': typeof DashboardSocialBrandRoute
  '/dashboard/social/campaigns': typeof DashboardSocialCampaignsRoute
  '/dashboard/social/schedule': typeof DashboardSocialScheduleRoute
  '/dashboard/social/studio': typeof DashboardSocialStudioRoute
  '/dashboard/social': typeof DashboardSocialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/for-floors': typeof ForFloorsRoute
  '/for-solo': typeof ForSoloRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/book/$salonKey': typeof BookSalonKeyRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/concierge': typeof DashboardConciergeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/ops': typeof DashboardOpsRoute
  '/dashboard/platform': typeof DashboardPlatformRoute
  '/dashboard/social': typeof DashboardSocialRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/social/brand': typeof DashboardSocialBrandRoute
  '/dashboard/social/campaigns': typeof DashboardSocialCampaignsRoute
  '/dashboard/social/schedule': typeof DashboardSocialScheduleRoute
  '/dashboard/social/studio': typeof DashboardSocialStudioRoute
  '/dashboard/social/': typeof DashboardSocialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/for-floors'
    | '/for-solo'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/book/$salonKey'
    | '/compare/$slug'
    | '/dashboard/calendar'
    | '/dashboard/clients'
    | '/dashboard/concierge'
    | '/dashboard/leads'
    | '/dashboard/ops'
    | '/dashboard/platform'
    | '/dashboard/social'
    | '/dashboard/'
    | '/dashboard/social/brand'
    | '/dashboard/social/campaigns'
    | '/dashboard/social/schedule'
    | '/dashboard/social/studio'
    | '/dashboard/social/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/for-floors'
    | '/for-solo'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/book/$salonKey'
    | '/compare/$slug'
    | '/dashboard/calendar'
    | '/dashboard/clients'
    | '/dashboard/concierge'
    | '/dashboard/leads'
    | '/dashboard/ops'
    | '/dashboard/platform'
    | '/dashboard'
    | '/dashboard/social/brand'
    | '/dashboard/social/campaigns'
    | '/dashboard/social/schedule'
    | '/dashboard/social/studio'
    | '/dashboard/social'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/for-floors'
    | '/for-solo'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/book/$salonKey'
    | '/compare/$slug'
    | '/dashboard/calendar'
    | '/dashboard/clients'
    | '/dashboard/concierge'
    | '/dashboard/leads'
    | '/dashboard/ops'
    | '/dashboard/platform'
    | '/dashboard/social'
    | '/dashboard/'
    | '/dashboard/social/brand'
    | '/dashboard/social/campaigns'
    | '/dashboard/social/schedule'
    | '/dashboard/social/studio'
    | '/dashboard/social/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForFloorsRoute: typeof ForFloorsRoute
  ForSoloRoute: typeof ForSoloRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BookSalonKeyRoute: typeof BookSalonKeyRoute
  CompareSlugRoute: typeof CompareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-solo': {
      id: '/for-solo'
      path: '/for-solo'
      fullPath: '/for-solo'
      preLoaderRoute: typeof ForSoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-floors': {
      id: '/for-floors'
      path: '/for-floors'
      fullPath: '/for-floors'
      preLoaderRoute: typeof ForFloorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/social': {
      id: '/dashboard/social'
      path: '/social'
      fullPath: '/dashboard/social'
      preLoaderRoute: typeof DashboardSocialRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/platform': {
      id: '/dashboard/platform'
      path: '/platform'
      fullPath: '/dashboard/platform'
      preLoaderRoute: typeof DashboardPlatformRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ops': {
      id: '/dashboard/ops'
      path: '/ops'
      fullPath: '/dashboard/ops'
      preLoaderRoute: typeof DashboardOpsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/concierge': {
      id: '/dashboard/concierge'
      path: '/concierge'
      fullPath: '/dashboard/concierge'
      preLoaderRoute: typeof DashboardConciergeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$salonKey': {
      id: '/book/$salonKey'
      path: '/book/$salonKey'
      fullPath: '/book/$salonKey'
      preLoaderRoute: typeof BookSalonKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/social/': {
      id: '/dashboard/social/'
      path: '/'
      fullPath: '/dashboard/social/'
      preLoaderRoute: typeof DashboardSocialIndexRouteImport
      parentRoute: typeof DashboardSocialRoute
    }
    '/dashboard/social/studio': {
      id: '/dashboard/social/studio'
      path: '/studio'
      fullPath: '/dashboard/social/studio'
      preLoaderRoute: typeof DashboardSocialStudioRouteImport
      parentRoute: typeof DashboardSocialRoute
    }
    '/dashboard/social/schedule': {
      id: '/dashboard/social/schedule'
      path: '/schedule'
      fullPath: '/dashboard/social/schedule'
      preLoaderRoute: typeof DashboardSocialScheduleRouteImport
      parentRoute: typeof DashboardSocialRoute
    }
    '/dashboard/social/campaigns': {
      id: '/dashboard/social/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/social/campaigns'
      preLoaderRoute: typeof DashboardSocialCampaignsRouteImport
      parentRoute: typeof DashboardSocialRoute
    }
    '/dashboard/social/brand': {
      id: '/dashboard/social/brand'
      path: '/brand'
      fullPath: '/dashboard/social/brand'
      preLoaderRoute: typeof DashboardSocialBrandRouteImport
      parentRoute: typeof DashboardSocialRoute
    }
  }
}

interface DashboardSocialRouteChildren {
  DashboardSocialBrandRoute: typeof DashboardSocialBrandRoute
  DashboardSocialCampaignsRoute: typeof DashboardSocialCampaignsRoute
  DashboardSocialScheduleRoute: typeof DashboardSocialScheduleRoute
  DashboardSocialStudioRoute: typeof DashboardSocialStudioRoute
  DashboardSocialIndexRoute: typeof DashboardSocialIndexRoute
}

const DashboardSocialRouteChildren: DashboardSocialRouteChildren = {
  DashboardSocialBrandRoute: DashboardSocialBrandRoute,
  DashboardSocialCampaignsRoute: DashboardSocialCampaignsRoute,
  DashboardSocialScheduleRoute: DashboardSocialScheduleRoute,
  DashboardSocialStudioRoute: DashboardSocialStudioRoute,
  DashboardSocialIndexRoute: DashboardSocialIndexRoute,
}

const DashboardSocialRouteWithChildren = DashboardSocialRoute._addFileChildren(
  DashboardSocialRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardConciergeRoute: typeof DashboardConciergeRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardOpsRoute: typeof DashboardOpsRoute
  DashboardPlatformRoute: typeof DashboardPlatformRoute
  DashboardSocialRoute: typeof DashboardSocialRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardConciergeRoute: DashboardConciergeRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardOpsRoute: DashboardOpsRoute,
  DashboardPlatformRoute: DashboardPlatformRoute,
  DashboardSocialRoute: DashboardSocialRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForFloorsRoute: ForFloorsRoute,
  ForSoloRoute: ForSoloRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BookSalonKeyRoute: BookSalonKeyRoute,
  CompareSlugRoute: CompareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
